Repository add-eus/library, pull requests merged in 2024-03, with the labels that each got.

#141 feat: add croping default size
  components/base/VCrop.vue
Labels: enhancement, Review effort [1-5]: 2

#142 feat: new var
  components/base/accordion/VCollapse.vue
  components/base/form/VFile.vue
  scss/abstracts/_helpers.scss
  scss/abstracts/_variables.scss
  scss/css-variables/_fonts.scss
  scss/css-variables/_radius.scss
  vite.config.cjs
Labels: enhancement, Review effort [1-5]: 3

#143 Patch 1
  scss/layout/_responsive.scss
Labels: enhancement, Review effort [1-5]: 3

#145 fix: use import collection
  stores/firebase.ts
  stores/firestore/collection.ts
  stores/firestore/entity.ts
  stores/firestore/index.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#144 feat: add file size and video constraints
  components/base/form/VFile.vue
Labels: enhancement, Review effort [1-5]: 4

#146 build: update commitlint
  commitlint.config.cts
  package-lock.json
  package.json
Labels: enhancement, dependencies, Review effort [1-5]: 2
