Repository add-eus/library, pull requests merged in 2024-02, with the labels that each got.

#131 chore: refactoring some components
  components/base/accordion/VCollapse.vue
  components/base/button/VAction.vue
  components/base/icon/VIcon.vue
  components/base/tabs/VTabs.vue
  scss/components/_content.scss
  scss/css-variables/_colors.scss
  stores/color.ts
  stores/translate.ts
Labels: enhancement

#132 fix: change path in model.json generator for optimized ORM
  stores/firestore/security/cloudFunctionModel.ts
Labels: bug_fix, Review effort [1-5]: 2

#133 feat: expose VCollapse functions
  components/base/accordion/VCollapse.vue
Labels: enhancement

#135 fix: fix property rules
  stores/firestore/security/rules.ts
Labels: bug_fix, Review effort [1-5]: 3
